databases:
  - name: refz
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: fefz
    env: python
    buildCommand: pip install  -r requirements.txt
    startCommand: python3 server.py & python3 -m zthon 
    region: frankfurt
    envVars:
      - key: ALIVE_NAME
        sync: false
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: ENV
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: TZ
        value: Asia/Amman
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: refz
          property: connectionString   
      - key: HEROKU_API_KEY
   value: "FAKE_KEY_TO_BYPASS_HEROKU"
   - key: HEROKU_APP_NAME
  value: "FAKE_APP_NAME"
    autoDeploy: false
